# Infra stuff for key server

- name: Put parameters.yml
  template: src=parameters.yml.j2 dest={{ component_dir_name }}/app/config/parameters.yml mode={{ component_mode_640 }} group={{ component_group }}

- name: assets:install
  command: php app/console assets:install --symlink --env=prod {{ debug_flag }}
  args:
      chdir: "{{ component_dir_name }}"

- name: Dump Assetic Assets
  command: php app/console assetic:dump --env=prod {{ debug_flag }}
  args:
      chdir: "{{ component_dir_name }}"

- name: Clear cache
  command: php app/console cache:clear --env=prod {{ debug_flag }}
  args:
      chdir: "{{ component_dir_name }}"

- name: Restrict app dir to the application
  file: path={{item}} group={{ component_group }} mode="o=" recurse=yes
  with_items:
  - "{{ component_dir_name }}/app"

- name: Grant app write access to cache and log dirs
  file: path={{item}} group={{ component_group }} mode={{ component_mode_770 }} recurse=yes
  with_items:
  - "{{ component_dir_name }}/app/cache"
  - "{{ component_dir_name }}/app/logs"

# Finish

- name: Set stepup directory rights
  file: path={{ component_dir_name }} state=directory group={{ component_group }} mode={{ component_mode_755 }}

- name: Activate component
  file: src={{ component_dir_name }} dest=/opt/www/{{ keyserver_vhost_name }} state=link

- name: Put keyserver configuration script in /root/
  template: src={{ item }}.j2 dest=/root/{{ item }} group=root owner=root mode="500"
  with_items:
  - "01-keyserver-db_init.sh"